POST http://localhost:5000/auth/register
Content-Type: application/json

{
"userid":"jovel",
"username":"yovel",
"password":"1243"
}
###



POST http://localhost:5000/questions

###

GET http://localhost:5000/questions


###

POST http://localhost:5000/feedback/rate/1

###

POST http://localhost:5000/auth/logout

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "userid": "jovel",
    "password": "1243"
}

###
GET http://localhost:5000/auth/getuser/jovy6lsl2
###
GET http://localhost:3003/api/blogs

###