POST http://localhost:5000/auth/register
Content-Type: application/json

{
"userid":"hovel",
"username":"yovel",
"password":"1243"
}
###



POST http://localhost:5000/questions

###

GET http://localhost:5000/questions


###

PATCH  http://localhost:5000/feedback/rate/3
Content-Type: application/json

{
"rating": "1"
}

###

POST http://localhost:5000/feedback/comment/3
Content-Type: application/json

{
"feedback": "Great"
}

###

POST http://localhost:5000/auth/logout

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "userid": "jovel",
    "password": "1243"
}

###
GET http://localhost:5000/auth/getuser/jovy6lsl2
###
GET http://localhost:5000/auth/islogged
###
POST http://localhost:5000/feedback/comment/delete/3

###
DELETE  http://localhost:5000/auth/user/delete/hovel